service: noti-pyme-lambda

provider:
  name: aws
  runtime: python3.9
  region: us-east-1
  environment:
    JWT_SECRET: ${env:JWT_SECRET}
    TWILIO_ACCOUNT_SID: ${env:TWILIO_ACCOUNT_SID}
    TWILIO_AUTH_TOKEN: ${env:TWILIO_AUTH_TOKEN}
    TWILIO_PHONE_NUMBER: ${env:TWILIO_PHONE_NUMBER}
    EMAIL_FROM_ADDRESS: ${env:EMAIL_FROM_ADDRESS}
    AWS_REGION: ${env:AWS_REGION}

functions:
  sendNotification:
    handler: src/handlers/send_notification.handler
    events:
      - http:
          path: send
          method: post