name: Deploy to AWS on merge to main

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13.3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Install AWS CLI
        run: |
          sudo apt-get install awscli

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Cambia la región según tu caso

      - name: Create deployment package
        run: |
          # Si tu Lambda está en send_notification.py, empaquetamos el archivo y sus dependencias
          mkdir package
          cp src/handlers/send_notification.py package/
          pip install -r requirements.txt -t package/
          cd package && zip -r ../lambda-deployment.zip .

      - name: Deploy Lambda function
        run: |
          aws lambda update-function-code \
            --function-name send_notification \
            --zip-file fileb://lambda-deployment.zip
