name: Deploy to AWS on merge to main

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13.3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Install AWS CLI
        run: |
          pip install awscli

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Cambia la región según tu caso

      - name: Create deployment package
        run: |
          mkdir package
          cp src/handlers/send_notification.py package/
          pip install -r requirements.txt -t package/
          cd package && zip -r ../lambda-deployment.zip .

      - name: Deploy Lambda function
        run: |
          aws lambda update-function-code \
            --function-name send_notification \
            --zip-file fileb://lambda-deployment.zip

      - name: Verify if Lambda function exists
        id: check_lambda
        run: |
          if aws lambda get-function --function-name send_notification; then
            echo "Function exists, ready to update";
            echo "function_exists=true" >> $GITHUB_ENV;
          else
            echo "Function does not exist, ready to create";
            echo "function_exists=false" >> $GITHUB_ENV;
          fi

      - name: Update Lambda function code (if exists)
        if: env.function_exists == 'true'
        run: |
          aws lambda update-function-code \
            --function-name send_notification \
            --zip-file fileb://lambda-deployment.zip

      - name: Create Lambda function (if it does not exist)
        if: env.function_exists == 'false'
        run: |
          aws lambda create-function \
            --function-name send_notification \
            --runtime python3.8 \
            --role arn:aws:iam::your-account-id:role/send-notification-role \
            --handler send_notification.handler \
            --zip-file fileb://lambda-deployment.zip